# Generated by Django 3.2.16 on 2022-12-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221229_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='rendelo',
        ),
    ]
