# Generated by Django 3.2.16 on 2022-12-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_author_post_rendelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='italok',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pizza',
            field=models.CharField(max_length=255),
        ),
    ]
